apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 22.0.1
  name: icp4adeploy
  namespace: cp4ba
spec:
  bai_configuration:
    business_performance_center:
      all_users_access: true
    image_credentials:
      registry: cp.icr.io/cp/cp4a
  resource_registry_configuration:
    images:
      resource_registry:
        repository: cp.icr.io/cp/cp4a/aae/dba-etcd
        tag: 22.0.1
  ecm_configuration:
    cmis:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cmis
        tag: 22.0.1
    cpe:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/cpe
        tag: 22.0.1
    css:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/css
        tag: 22.0.1
    document_processing:
      cdra:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/cdra
          tag: 22.0.1
      cds:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/cds
          tag: 22.0.1
      cpds:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/cpds
          tag: 22.0.1
      gitgateway:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/gitgateway
          tag: 22.0.1
      mongo:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/mongo_adp
          tag: 4.2.19
      viewone:
        image:
          repository: cp.icr.io/cp/cp4a/iadp/viewone
          tag: 22.0.1
    graphql:
      graphql_production_setting:
        enable_graph_iql: true
      image:
        repository: cp.icr.io/cp/cp4a/fncm/graphql
        tag: 22.0.1
    tm:
      image:
        repository: cp.icr.io/cp/cp4a/fncm/taskmgr
        tag: 22.0.1
  ads_configuration:
    run_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-run
        tag: 22.0.1
    parsing_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-parsing
        tag: 22.0.1
    git_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-gitservice
        tag: 22.0.1
    front:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-front
        tag: 22.0.1
    decision_runtime_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-runtime
        tag: 22.0.1
    decision_designer:
      enabled: true
    embedded_build_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-build
        tag: 22.0.1
    rest_api:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-restapi
        tag: 22.0.1
    credentials_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-credentials
        tag: 22.0.1
    rr_integration:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-rrintegration
        tag: 22.0.1
    decision_runtime:
      enabled: true
    download_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-download
        tag: 22.0.1
  bastudio_configuration:
    images:
      bastudio:
        repository: cp.icr.io/cp/cp4a/bas/bastudio
        tag: 22.0.1
    jms_server:
      image:
        repository: cp.icr.io/cp/cp4a/bas/jms
        tag: 22.0.1
    playback_server:
      images:
        db_job:
          repository: cp.icr.io/cp/cp4a/bas/solution-server-helmjob-db
          tag: 22.0.1
        solution_server:
          repository: cp.icr.io/cp/cp4a/bas/solution-server
          tag: 22.0.1
  ier_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ier/ier
      tag: 22.0.1
  workflow_authoring_configuration:
    bas_auto_import_job:
      repository: cp.icr.io/cp/cp4a/baw/toolkit-installer
      tag: 22.0.1
    case:
      init_job_image:
        repository: cp.icr.io/cp/cp4a/baw/workflow-server-case-initialization
        tag: 22.0.1
    content_integration:
      init_job_image:
        repository: cp.icr.io/cp/cp4a/baw/iaws-ps-content-integration
        tag: 22.0.1
    ibm_workplace_job:
      repository: cp.icr.io/cp/cp4a/baw/iaws-ibm-workplace
      tag: 22.0.1
    image:
      repository: cp.icr.io/cp/cp4a/bas/workflow-authoring
      tag: 22.0.1
    jms:
      image:
        repository: cp.icr.io/cp/cp4a/baw/jms
        tag: 22.0.1
    pfs_bpd_database_init_job:
      repository: cp.icr.io/cp/cp4a/baw/pfs-bpd-database-init-prod
      tag: 22.0.1
    upgrade_job:
      repository: cp.icr.io/cp/cp4a/baw/workflow-server-dbhandling
      tag: 22.0.1
  navigator_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/ban/navigator
      tag: 22.0.1
  odm_configuration:
    decisionCenter:
      enabled: true
    decisionRunner:
      enabled: true
    decisionServerRuntime:
      enabled: true
    image:
      pullSecrets: ibm-entitlement-key
      repository: cp.icr.io/cp/cp4a/odm
  pfs_configuration:
    image:
      repository: cp.icr.io/cp/cp4a/baw/pfs-prod
      tag: 22.0.1
  baml_configuration:
    intelligent_task_prioritization:
      image:
        repository: cp.icr.io/cp/cp4a/baw/bui-task-prioritization
        tag: 22.0.1
    workforce_insights:
      image:
        repository: cp.icr.io/cp/cp4a/baw/workforce-insights
        tag: 22.0.1
  ca_configuration:
    deeplearning:
      gpu_enabled: false
      nodelabel_key: null
      nodelabel_value: null
    global:
      image:
        repository: cp.icr.io/cp/cp4a/iadp
        tag: 22.0.1
      oneconversion:
        enabled: false
  ibm_license: accept
  appVersion: 22.0.1
  shared_configuration:
    sc_cpe_limited_storage: false
    sc_deployment_type: Starter
    sc_optional_components: >-
      ads_designer,ads_runtime,bai,baml,ban,baw_authoring,case,cmis,content_integration,css,decisionCenter,decisionRunner,decisionServerRuntime,document_processing_designer,ier,pfs,tm,workstreams
    sc_drivers_url: null
    image_pull_secrets:
      - ibm-entitlement-key
    trusted_certificate_list: []
    sc_deployment_patterns: >-
      foundation,application,content,decisions,decisions_ads,document_processing,workflow-workstreams
    sc_deployment_baw_license: non-production
    storage_configuration:
      sc_block_storage_classname: ibmc-block-gold
      sc_dynamic_storage_classname: ibmc-file-gold-gid
      sc_fast_file_storage_classname: ibmc-file-gold-gid
      sc_medium_file_storage_classname: ibmc-file-gold-gid
      sc_slow_file_storage_classname: ibmc-file-gold-gid
    root_ca_secret: '{{ meta.name }}-root-ca'
    sc_run_as_user: null
    sc_content_initialization: true
    sc_deployment_license: non-production
    images:
      dbcompatibility_init_container:
        repository: cp.icr.io/cp/cp4a/aae/dba-dbcompatibility-initcontainer
        tag: 22.0.1
      gitea:
        repository: cp.icr.io/cp/cp4a/demo/gitea
        tag: 1.16.7
      keytool_init_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-initcontainer
        tag: 22.0.1
      keytool_job_container:
        repository: cp.icr.io/cp/cp4a/ums/dba-keytool-jobcontainer
        tag: 22.0.1
      openldap:
        repository: cp.icr.io/cp/cp4a/demo/openldap
        tag: 1.5.0.1
      umsregistration_initjob:
        repository: cp.icr.io/cp/cp4a/aae/dba-umsregistration-initjob
        tag: 22.0.1
    sc_ingress_enable: false
    sc_image_repository: cp.icr.io
    sc_deployment_platform: ROKS
    sc_deployment_fncm_license: non-production




