apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/cp4ba-admin.registrykey.yaml
  - base/cp4ba-cp4ba-operator.yaml
  - base/cp4ba-ibm-entitlement-key.yaml
  - base/namespace-cp4ba.yaml
