apiVersion: v1
kind: Namespace
metadata:
  name: cp4ba
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cp4ba-operator-group
  namespace: cp4ba
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - cp4ba
---
