apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4ba-ibm-entitlement-key
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cp4ba
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cp4ba/ibm-entitlement-key
    repoURL: https://github.com/brahm-cp4ba/cp4ba-repository-odm.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
